api_platform:

    title: 'BileMo'
    description: 'API catalogue de téléphones haut de gamme'
    version: '0.1.0'

    formats:
        jsonld:   ['application/ld+json']
        jsonhal:  ['application/hal+json']
        jsonapi:  ['application/vnd.api+json']
        json:     ['application/json']
        yaml:     ['application/x-yaml']
        xml:      ['application/xml', 'text/xml']
        html:     ['text/html']

    mapping:
        paths: ['%kernel.project_dir%/config/api_platform/resources']

    patch_formats:
        json: ['application/merge-patch+json']

    defaults:
        cache_headers:
            etag: true
            max_age: 120
            shared_max_age: 3600
            vary: ['Content-Type', 'Authorization', 'Origin']

    http_cache:
        invalidation:
            enabled: true
            # varnish_urls: ['%env(VARNISH_URL)%']
        public: true

    swagger:
        versions: [3]
        api_keys:
          apiKey:
            name: Authorization
            type: header

    show_webby: false
