# app/config/api_platform/resources/

App\Entity\Brand:
  attributes:
    formats: [jsonld, jsonhal, json, xml]
    pagination_items_per_page: 10
    pagination_maximum_items_per_page: 20
    pagination_client_items_per_page: true

  collectionOperations:
    get:
      normalization_context:
        groups: [read:Brand:collection]
        openapi_definition_name: Collection
    post:
      # security: is_granted("ROLE_ADMIN")
      denormalization_context:
        groups: [write:Brand]
      openapi_context:
        summary: Creates a Brand resource (Admin only).
        description: Creates a Brand resource (Admin only).

  itemOperations:
    get:
      normalization_context:
        groups: [read:Brand:item, read:Brand:collection]
        openapi_definition_name: Item
    put: 
      # security: is_granted("ROLE_ADMIN")
      denormalization_context:
        groups: [write:Brand]
      openapi_context:
        summary: Replaces the Brand resource (Admin only).
        description: Replaces the Brand resource (Admin only).        
    patch:
      # security: is_granted("ROLE_ADMIN")
      denormalization_context:
        groups: [write:Brand]
      openapi_context:
        summary: Updates the Brand resource (Admin only).
        description: Updates the Brand resource (Admin only).        
    delete:
      # security: is_granted("ROLE_ADMIN")
      openapi_context:
        summary: Removes the Brand resource (Admin only).
        description: Removes the Brand resource (Admin only).      
