# app/config/api_platform/resources/

App\Entity\Phone:
  attributes:
    security: is_granted("ROLE_USER")
    formats: [jsonld, jsonhal, json, xml]   
    pagination_items_per_page: 10
    pagination_maximum_items_per_page: 20
    pagination_client_items_per_page: true
    validation_groups: [write:Phone]
    denormalization_context:
      groups: [write:Phone]
      openapi_definition_name: Collection
    normalization_context:
      groups: [read:Phone:item, read:Phone:collection]
      openapi_definition_name: Item

  collectionOperations:
    get:
      normalization_context:
        groups: [read:Phone:collection]
    post:
      security: is_granted("ROLE_ADMIN")
      denormalization_context:
        groups: [write:Phone]
      normalization_context:
        groups: [read:Phone:item, read:Phone:collection]        
      openapi_context:
        summary: Creates a Phone resource (Admin only).
        description: Creates a Phone resource (Admin only).        
    count:
      method: GET
      path: /phones/count
      controller: App\Controller\PhoneController
      filters: []
      pagination_enabled: false
      openapi_context:
        summary: Retrieves total number of phones.
        description: Retrieves total number of phones.
        parameters:
          - 
            in: query
            name: brand
            example: Wiplo
            description: Filters by brand(s) name or id.
        responses:
          200:
            description: Number of phones
            content:
              application/json:
                schema:
                  type: integer
                  example: 24

  itemOperations: 
    get:
      normalization_context:
        groups: [read:Phone:item, read:Phone:collection]
    put:
      security: is_granted("ROLE_ADMIN")
      validation_groups: [replace:Phone]        
      openapi_context:
        summary: Replaces the Phone resource (Admin only).
        description: Replaces the Phone resource (Admin only).
    patch:
      security: is_granted("ROLE_ADMIN")
      validation_groups: [update:Phone]      
      openapi_context:
        summary: Updates the Phone resource (Admin only).
        description: Updates the Phone resource (Admin only).
      denormalization_context:
        groups: [update:Phone]
    delete:
      security: is_granted("ROLE_ADMIN")
      openapi_context:
        summary: Removes the Phone resource (Admin only).
        description: Removes the Phone resource (Admin only).               
