# app/config/api_platform/resources/

App\Entity\User:
  attributes: 
    security: is_granted("ROLE_USER")
    formats: [jsonld, jsonhal, json, xml]   
    pagination_items_per_page: 10
    pagination_maximum_items_per_page: 20
    pagination_client_items_per_page: true
    validation_groups: ['write:User']
    denormalization_context:
      groups: [write:User]
      openapi_definition_name: Item
    normalization_context:
      groups: [read:User:collection]
      openapi_definition_name: Collection

  collectionOperations:
    get: ~
    post:
      denormalization_context:
        groups: [write:User]

  itemOperations:
    get:
      normalization_context:
        groups: [read:User:item, read:User:collection]
        openapi_definition_name: Item
    patch:
      # thanks to App\Doctrine\CurrentUserExtension, 
      # current User will not be able to update Client
      security: 'is_granted("EDIT", object)'
      validation_groups: ['update:User']
      denormalization_context:
        groups: ['update:User']
    delete:
      security: 'is_granted("DELETE", object)'
      openapi_context:
        responses:
            403:
              description: Access Denied
    me:
      method: GET
      path: /me
      controller: App\Controller\UserMeController
      read: false
      normalization_context:
        groups: [read:User:item, read:User:collection]
      openapi_context:
        summary: Retrieves current authenticated User.
        description: Retrieves current authenticated User.
      
