#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# gesdinet JWT token refresh
gesdinet_jwt_refresh_token:
    path: /api/token/refresh
    controller: gesdinet.jwtrefreshtoken::refresh