# app/config/serialization/

App\Entity\Client:
  attributes:
    id:
      groups: [read:Client:item, read:User:item]
    name:
      groups: [read:Client:item, read:Client:collection, write:Client, read:User:item, read:User:collection]      
    users:
      groups: [read:Client:item]
    createdAt:
      groups: [read:Client:collection, read:User:item]
