# app/config/serialization/

App\Entity\User:
  attributes:
    id:
      groups: [read:User:collection]
    email:
      groups: [read:User:collection, update:User, write:User]
    roles:
      groups: [read:User:item]
    password:
      groups: [write:User]
    client:
      groups: [read:User:item, update:User, read:User:collection]
